import { TradeMeasure, MeasureEvent, LegalChallenge, TradeFlow, PortSignal, SupplyDisruption } from './types';

export const SEED_MEASURES: TradeMeasure[] = [
  {
    id: "meas-us-ieepa-2025",
    version: 1,
    supersedes: null,
    title: "Global 10% Emergency Duties (IEEPA Basis)",
    kind: "tariff",
    imposing_country: "USA",
    target_countries: ["ALL"],
    hs_codes: ["ALL"],
    product_summary: "All merchandise imports under emergency authorities",
    rate_text: "10%",
    rate_numeric: 10.0,
    rate_unit: "percent_ad_valorem",
    legal_instrument: "International Emergency Economic Powers Act (IEEPA)",
    instrument_url: "https://www.congress.gov/crs-product/LSB11398",
    effective_from: "2025-02-01",
    effective_to: "2026-02-20",
    status: "struck_down",
    exclusion_process: "Lapsed under Supreme Court ruling",
    trigger_measure_id: null,
    source_id: "scotusblog",
    source_url: "https://www.scotusblog.com/2026/02/supreme-court-strikes-down-tariffs/",
    is_seed: true,
  },
  {
    id: "meas-us-statutory-80ctry-2026",
    version: 1,
    supersedes: null,
    title: "10%–12.5% Statutory Duties on 80+ Countries",
    kind: "tariff",
    imposing_country: "USA",
    target_countries: ["CHN", "VNM", "MYS", "IND", "THA", "IDN", "BRA", "TUR", "ZAF", "EGY"],
    hs_codes: ["ALL"],
    product_summary: "Comprehensive consumer & industrial merchandise imports",
    rate_text: "10%–12.5%",
    rate_numeric: 12.5,
    rate_unit: "percent_ad_valorem",
    legal_instrument: "Presidential Proclamation & Trade Act Authorities",
    instrument_url: "https://www.federalregister.gov",
    effective_from: "2026-07-23",
    effective_to: null,
    status: "in_force",
    exclusion_process: "Commerce Department Annex III Review",
    trigger_measure_id: null,
    source_id: "federal_register",
    source_url: "https://www.nytimes.com/2026/07/23/business/economy/trump-tariffs.html",
    is_seed: true,
  },
  {
    id: "meas-can-retaliation-2026",
    version: 1,
    supersedes: null,
    title: "Canada Counter-Tariffs on Targeted US Products",
    kind: "tariff",
    imposing_country: "CAN",
    target_countries: ["USA"],
    hs_codes: ["02", "04", "22", "72", "73", "84", "87"],
    product_summary: "Steel, aluminum, motor vehicles, dairy & consumer foodstuffs",
    rate_text: "15/25/50%",
    rate_numeric: null, // Tiered compound rates: 15%, 25%, and 50%
    rate_unit: "compound_or_tiered",
    legal_instrument: "Customs Tariff Act (Department of Finance Order in Council)",
    instrument_url: "https://www.canada.ca/en/department-finance/news/2026/08/list-of-products-from-the-united-states-subject-to-counter-tariffs-effective-september-8-2026.html",
    effective_from: "2026-09-08",
    effective_to: null,
    status: "in_force",
    exclusion_process: "Section 115 Remission Requests",
    trigger_measure_id: "meas-us-statutory-80ctry-2026",
    source_id: "fin_canada",
    source_url: "https://www.canada.ca/en/department-finance/news/2026/08/list-of-products-from-the-united-states-subject-to-counter-tariffs-effective-september-8-2026.html",
    is_seed: true,
  },
  {
    id: "meas-us-de-minimis-2025",
    version: 1,
    supersedes: null,
    title: "Universal De Minimis Exemption Suspension ($800 Threshold)",
    kind: "ban",
    imposing_country: "USA",
    target_countries: ["ALL"],
    hs_codes: ["ALL"],
    product_summary: "Low-value commercial parcel imports without formal entry",
    rate_text: "Statutory Duty Applicable",
    rate_numeric: null,
    rate_unit: "statutory_ad_valorem",
    legal_instrument: "Executive Action on Section 321 Tariff Act of 1930",
    instrument_url: "https://ustr.gov/trade-topics/presidential-tariff-actions",
    effective_from: "2025-08-01",
    effective_to: null,
    status: "in_force",
    exclusion_process: null,
    trigger_measure_id: null,
    source_id: "ustr",
    source_url: "https://ustr.gov/trade-topics/presidential-tariff-actions",
    is_seed: true,
  },
  {
    id: "meas-eu-threat-auto-2026",
    version: 1,
    supersedes: null,
    title: "EU Automotive Escalation Tariff Threat (15% → 25%)",
    kind: "tariff",
    imposing_country: "EA",
    target_countries: ["USA"],
    hs_codes: ["87"],
    product_summary: "Passenger vehicles and light commercial trucks",
    rate_text: "25%",
    rate_numeric: 25.0,
    rate_unit: "percent_ad_valorem",
    legal_instrument: "Proposed Enforcement Regulation (Unratified)",
    instrument_url: "https://www.atlanticcouncil.org/programs/geoeconomics-center/trump-tariff-tracker/",
    effective_from: "2026-07-04",
    effective_to: null,
    status: "proposed",
    exclusion_process: null,
    trigger_measure_id: "meas-us-statutory-80ctry-2026",
    source_id: "atlantic_council",
    source_url: "https://www.atlanticcouncil.org/programs/geoeconomics-center/trump-tariff-tracker/",
    is_seed: true,
    is_tracker_only: true, // Deliberate test of the tracker-only invariant
  }
];

export const SEED_LEGAL_CHALLENGES: LegalChallenge[] = [
  {
    id: "scotus-ieepa-2026",
    court: "Supreme Court of the United States",
    case_name: "Importers Coalition v. United States (IEEPA Scope)",
    filed_date: "2025-06-12",
    decided_date: "2026-02-20",
    outcome: "IEEPA Tariffs Struck Down (6-3)",
    affected_measure_ids: ["meas-us-ieepa-2025"],
    summary: "The Supreme Court ruled that the International Emergency Economic Powers Act does not authorize unilateral imposition of broad import duties absent specific statutory tax delegation.",
    source_url: "https://www.scotusblog.com/2026/02/supreme-court-strikes-down-tariffs/",
  }
];

export const SEED_FLOWS: TradeFlow[] = [
  {
    id: "flow-chn-usa-85",
    reporter_iso: "USA",
    partner_iso: "CHN",
    hs_code: "85",
    product_summary: "Electrical machinery and electronics equipment",
    period_label: "Q2 2026",
    period_start: "2026-04-01",
    direction: "import",
    value_usd: 34200000000,
    volume: null,
    volume_unit: null,
    yoy_pct: 4.8,
    source_id: "un_comtrade",
    source_url: "https://comtradeapi.un.org",
  },
  {
    id: "flow-can-usa-87",
    reporter_iso: "USA",
    partner_iso: "CAN",
    hs_code: "87",
    product_summary: "Motor vehicles and automotive components",
    period_label: "Q2 2026",
    period_start: "2026-04-01",
    direction: "import",
    value_usd: 18500000000,
    volume: null,
    volume_unit: null,
    yoy_pct: -6.2,
    source_id: "un_comtrade",
    source_url: "https://comtradeapi.un.org",
  },
  {
    id: "flow-ea-usa-84",
    reporter_iso: "USA",
    partner_iso: "EA",
    hs_code: "84",
    product_summary: "Nuclear reactors, boilers, machinery & mechanical appliances",
    period_label: "Q2 2026",
    period_start: "2026-04-01",
    direction: "import",
    value_usd: 28400000000,
    volume: null,
    volume_unit: null,
    yoy_pct: 1.5,
    source_id: "un_comtrade",
    source_url: "https://comtradeapi.un.org",
  }
];

export const SEED_PORT_SIGNALS: PortSignal[] = [
  {
    id: "port-la-dwell",
    port_id: "USLAX",
    port_name: "Port of Los Angeles / Long Beach",
    country_iso: "USA",
    metric: "dwell_days",
    period_label: "Sep 2026",
    value: 3.8,
    unit: "days",
    yoy_pct: -12.0,
    source_id: "port_authorities",
    source_url: "https://www.portoflosangeles.org",
  },
  {
    id: "port-rotterdam-queue",
    port_id: "NLRTM",
    port_name: "Port of Rotterdam",
    country_iso: "NLD",
    metric: "queue_vessels",
    period_label: "Sep 2026",
    value: 14,
    unit: "vessels",
    yoy_pct: 8.5,
    source_id: "port_authorities",
    source_url: "https://www.portofrotterdam.com",
  }
];

export const SEED_DISRUPTIONS: SupplyDisruption[] = [
  {
    id: "disrupt-suez-transit",
    kind: "canal_disruption",
    title: "Suez Canal Transit Volume Rerouting via Cape of Good Hope",
    hs_codes: ["ALL"],
    countries: ["EGY", "YEM"],
    severity: "high",
    started_at: "2024-01-15",
    resolved_at: null,
    summary: "Container vessel diversions around Africa adding 10-14 days transit dwell between Asia and Northern Europe.",
    source_urls: ["https://www.reuters.com"],
  }
];
